insert into authors (id, first_name, last_name) values (1, 'Ebony', 'Mohammad');
insert into authors (id, first_name, last_name) values (2, 'Steve', 'Benjefield');
insert into authors (id, first_name, last_name) values (3, 'Sunshine', 'Winkworth');
insert into authors (id, first_name, last_name) values (4, 'Woodrow', 'Willis');
insert into authors (id, first_name, last_name) values (5, 'Midge', 'Huntly');
insert into authors (id, first_name, last_name) values (6, 'Stormy', 'Guyon');
insert into authors (id, first_name, last_name) values (7, 'Brandice', 'Ryal');
insert into authors (id, first_name, last_name) values (8, 'Cammy', 'Denny');
insert into authors (id, first_name, last_name) values (9, 'Lewiss', 'Bilt');
insert into authors (id, first_name, last_name) values (10, 'Kelli', 'Lownes');
insert into authors (id, first_name, last_name) values (11, 'Nilson', 'Borrill');
insert into authors (id, first_name, last_name) values (12, 'Robbin', 'Cutchey');
insert into authors (id, first_name, last_name) values (13, 'Lorrie', 'Hutten');
insert into authors (id, first_name, last_name) values (14, 'Phedra', 'Garnar');
insert into authors (id, first_name, last_name) values (15, 'Leonidas', 'Storah');
insert into authors (id, first_name, last_name) values (16, 'Darryl', 'Besemer');
insert into authors (id, first_name, last_name) values (17, 'Lisle', 'Milliken');
insert into authors (id, first_name, last_name) values (18, 'Michaelina', 'Legier');
insert into authors (id, first_name, last_name) values (19, 'Flynn', 'M''Quharge');
insert into authors (id, first_name, last_name) values (20, 'Krystyna', 'Rizzillo');
insert into authors (id, first_name, last_name) values (21, 'Oliviero', 'Gorghetto');

insert into books (id, price, price_old, title, author_id) values (1, 496, 93, 'Y-find', 4);
insert into books (id, price, price_old, title, author_id) values (2, 408, 26, 'Treeflex', 12);
insert into books (id, price, price_old, title, author_id) values (3, 827, 73, 'Stringtough', 21);
insert into books (id, price, price_old, title, author_id) values (4, 131, 9, 'Stronghold', 3);
insert into books (id, price, price_old, title, author_id) values (5, 468, 79, 'Zamit', 5);
insert into books (id, price, price_old, title, author_id) values (6, 209, 13, 'Matsoft', 2);
insert into books (id, price, price_old, title, author_id) values (7, 465, 29, 'Greenlam', 18);
insert into books (id, price, price_old, title, author_id) values (8, 753, 40, 'Y-Solowarm', 16);
insert into books (id, price, price_old, title, author_id) values (9, 889, 11, 'Zontrax', 20);
insert into books (id, price, price_old, title, author_id) values (10, 832, 13, 'Asoka', 8);
insert into books (id, price, price_old, title, author_id) values (11, 967, 27, 'Fixflex', 4);
insert into books (id, price, price_old, title, author_id) values (12, 842, 37, 'Stringtough', 11);
insert into books (id, price, price_old, title, author_id) values (13, 599, 17, 'Konklab', 13);
insert into books (id, price, price_old, title, author_id) values (14, 324, 20, 'Quo Lux', 19);
insert into books (id, price, price_old, title, author_id) values (15, 172, 16, 'Mat Lam Tam', 3);
insert into books (id, price, price_old, title, author_id) values (16, 593, 89, 'Alphazap', 8);
insert into books (id, price, price_old, title, author_id) values (17, 874, 27, 'Span', 14);
insert into books (id, price, price_old, title, author_id) values (18, 679, 2, 'Daltfresh', 11);
insert into books (id, price, price_old, title, author_id) values (19, 766, 39, 'Lotstring', 5);
insert into books (id, price, price_old, title, author_id) values (20, 286, 3, 'Opela', 18);
insert into books (id, price, price_old, title, author_id) values (21, 172, 20, 'Fintone', 1);
